# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6e39c7807552a757d8df73ff3cf4ad42ad02a3bc31cd80ac47915d4aa69c3c69f6db4d138382e5372ae401da7126a86decea6ed9975842341e38c941bad292

test:
  secret_key_base: e27db61dc13f33ad9d2bf2c8168efdc0f9e526747248f6b9ba0921c57cb9172b963717da2b772931eb54f915828913dcd90118285cde7b81f6835cc3a887200e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
